- users/_payhoob.php
- users/thalisearch.php
> payhoob done. only look wise needs to be improved if MH can do it please?

- users/thalisearch.php
On ThaaliSearch page results, hijri data was not showing in full format. It is now corrected.
> On ThaaliSearch page results, hijri data was not showing in full format. It is now corrected.

- users/_payhoob.php
Modifying the payhoob to first update the receipt table and than the thalilist table.
Also capturing any db related errors.
> Modifying the payhoob to first update the receipt table

- users/pendingactions.php
Now setting it to 0 as it affects count.
> Changed a flow in NR. We were having the NR as Active 1.

- sms/filter.js
- sms/index.php
- sms/selection.js
- sms/send.php
made it mobile friendly
@yusuf4u52 i have removed the two pages, and merged them into one
> responsive ui

- users/_stop_thali_admin.php
- users/adminsession.php
- users/index.php
- users/javascript/index.js
- users/stopMultipleThaalis.php
- users/thalisearch.php
apart from this I've also added a new page from where multiple thaalis can be stopped
stopMultipleThaalis.php. It asks for confirmation of each thaali before stopping to workaround typo problem
> fixed #37 i.e Have stop thali button available against a searched thali on thalisearch page

- users/stopMultipleThaalis.php
> #37 validations and trimming etc minor things

- users/_authCheck.php
- users/_bottomJS.php
- users/_head.php
- users/_nav.php
- users/_template.php
- users/index.php
- users/stopMultipleThaalis.php
- users/thalisearch.php
Code organization and an attempt to stay DRY.
> Being DRY (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

- users/_authCheck.php
- users/_bottomJS.php
- users/_head.php
- users/_nav.php
- users/_template.php
- users/hoobHistory.php
- users/index.php
- users/stopMultipleThaalis.php
- users/thalisearch.php
Merge/review this after https://github.com/murtaza52/faiz-static/pull/140, so that you can see changes of this task only.
> Hoob history for students fixes #11

- admin/application/controllers/Examples.php
- registration/index.php
> Occupation in registration

- index.html
- registration/index.php
- sms/index.php
- users/expenses.php
NR flow email after registration
> NR flow email after registration

- index.html
> fixed typo for registration

- sms/filter.js
- sms/index.php
go through the diff before committing. tested locally and works
> added active/inactive support

- sms/index.php
MRaja to work on UI option to give a toggle between next install and total pending.
> next install hardcoded in sms for now.

- sms/index.php
you can choose from next_install or Total_Pending
> sms filter now includes amount type

- sms/selection.js
the amount was not showing when next installment was selected. i added an or selector that does the trick
> amount not showing in sms

- sms/selection.js
the bug:
if you select 'n' random records, then first 'n' records' amount is reflected in output
reason:
i don't know jquery selectors and filtering mechanism :(
solution:
changed the line which was the culprit
> bug fix - selected record's amount not reflected

- sms/send.php
i havent checked it locally but it should work
> suffix support added

- users/_daily_hisab_entry.php
daily hisaab entry updated with per item cost. No database updates.
> _daily_hisab_entry updated with per item cost.

- sms/_helper.php
- users/_payhoob.php
changes:
1. As suggested by MH, added helper functions for Total_Pending
2. As requested by MM, changed the hub payment SMS template
3. As suggested by YR, removed the double bhais and bais
> changed hoob payment template, added helper.php

- users/_stop_thali_admin.php
- users/index.php
- users/src/custom.min.css
- users/stopMultipleThaalis.php
Salaam Yusuf bhai,
This is not working for a useless and silly error. Can you check at your end as it may be my MySQL causing it. SQL seems all good to me and it also executes on phpMyAdmin. 
`
UPDATE thalilist set Active='0', Thali_stop_date = '1439-08-20' WHERE Thali in (104,109);
UPDATE change_table set processed = 1 WHERE Thali in (104,109) and `Operation` in ('Start Thali','Stop Thali','Start Transport','Stop Transport') and processed = 0;
INSERT INTO change_table (`Thali`, `Operation`, `Date`) VALUES ('104', 'Stop Thali','1439-08-20');
INSERT INTO change_table (`Thali`, `Operation`, `Date`) VALUES ('109', 'Stop Thali','1439-08-20');
`
> NOT WORKING - Please check

- users/_authCheck.php
- users/_nav.php
- users/_stop_thali_admin.php
- users/musaid.php
- users/thalisearch.php
1. Musaid link now available in the menu
2. Musaid table horizontal scroll fixed
3. Start/Stop thali action available for musaids
4. Thali Active/Inactive status column added in table
> Musaid module changes
